// Token kinds, and the fixed text of those that have any.
//
// Generated by `tools/gen_token_kinds.py` from ponyc's `lexer.c`. The
// kinds are ponyc's `symbols` and `keywords` tables verbatim, plus the
// tokens whose text varies, plus the trivia and error kinds a lossless
// tree needs and a batch compiler does not. Do not edit by hand.

primitive TkEllipsis
  """
  The `...` symbol.
  """
  fun name(): String val => "TkEllipsis"
  fun text(): (String val | None) => "..."

primitive TkArrow
  """
  The `->` symbol.
  """
  fun name(): String val => "TkArrow"
  fun text(): (String val | None) => "->"

primitive TkDblarrow
  """
  The `=>` symbol.
  """
  fun name(): String val => "TkDblarrow"
  fun text(): (String val | None) => "=>"

primitive TkLshiftTilde
  """
  The `<<~` symbol.
  """
  fun name(): String val => "TkLshiftTilde"
  fun text(): (String val | None) => "<<~"

primitive TkRshiftTilde
  """
  The `>>~` symbol.
  """
  fun name(): String val => "TkRshiftTilde"
  fun text(): (String val | None) => ">>~"

primitive TkEqTilde
  """
  The `==~` symbol.
  """
  fun name(): String val => "TkEqTilde"
  fun text(): (String val | None) => "==~"

primitive TkNeTilde
  """
  The `!=~` symbol.
  """
  fun name(): String val => "TkNeTilde"
  fun text(): (String val | None) => "!=~"

primitive TkLeTilde
  """
  The `<=~` symbol.
  """
  fun name(): String val => "TkLeTilde"
  fun text(): (String val | None) => "<=~"

primitive TkGeTilde
  """
  The `>=~` symbol.
  """
  fun name(): String val => "TkGeTilde"
  fun text(): (String val | None) => ">=~"

primitive TkLtTilde
  """
  The `<~` symbol.
  """
  fun name(): String val => "TkLtTilde"
  fun text(): (String val | None) => "<~"

primitive TkGtTilde
  """
  The `>~` symbol.
  """
  fun name(): String val => "TkGtTilde"
  fun text(): (String val | None) => ">~"

primitive TkPlusTilde
  """
  The `+~` symbol.
  """
  fun name(): String val => "TkPlusTilde"
  fun text(): (String val | None) => "+~"

primitive TkMinusTilde
  """
  The `-~` symbol.
  """
  fun name(): String val => "TkMinusTilde"
  fun text(): (String val | None) => "-~"

primitive TkMultiplyTilde
  """
  The `*~` symbol.
  """
  fun name(): String val => "TkMultiplyTilde"
  fun text(): (String val | None) => "*~"

primitive TkDivideTilde
  """
  The `/~` symbol.
  """
  fun name(): String val => "TkDivideTilde"
  fun text(): (String val | None) => "/~"

primitive TkModTilde
  """
  The `%%~` symbol.
  """
  fun name(): String val => "TkModTilde"
  fun text(): (String val | None) => "%%~"

primitive TkRemTilde
  """
  The `%~` symbol.
  """
  fun name(): String val => "TkRemTilde"
  fun text(): (String val | None) => "%~"

primitive TkLshift
  """
  The `<<` symbol.
  """
  fun name(): String val => "TkLshift"
  fun text(): (String val | None) => "<<"

primitive TkRshift
  """
  The `>>` symbol.
  """
  fun name(): String val => "TkRshift"
  fun text(): (String val | None) => ">>"

primitive TkEq
  """
  The `==` symbol.
  """
  fun name(): String val => "TkEq"
  fun text(): (String val | None) => "=="

primitive TkNe
  """
  The `!=` symbol.
  """
  fun name(): String val => "TkNe"
  fun text(): (String val | None) => "!="

primitive TkLe
  """
  The `<=` symbol.
  """
  fun name(): String val => "TkLe"
  fun text(): (String val | None) => "<="

primitive TkGe
  """
  The `>=` symbol.
  """
  fun name(): String val => "TkGe"
  fun text(): (String val | None) => ">="

primitive TkChain
  """
  The `.>` symbol.
  """
  fun name(): String val => "TkChain"
  fun text(): (String val | None) => ".>"

primitive TkSubtype
  """
  The `<:` symbol.
  """
  fun name(): String val => "TkSubtype"
  fun text(): (String val | None) => "<:"

primitive TkBackslash
  """
  The `\` symbol.
  """
  fun name(): String val => "TkBackslash"
  fun text(): (String val | None) => "\\"

primitive TkAtLbrace
  """
  The `@{` symbol.
  """
  fun name(): String val => "TkAtLbrace"
  fun text(): (String val | None) => "@{"

primitive TkLbrace
  """
  The `{` symbol.
  """
  fun name(): String val => "TkLbrace"
  fun text(): (String val | None) => "{"

primitive TkRbrace
  """
  The `}` symbol.
  """
  fun name(): String val => "TkRbrace"
  fun text(): (String val | None) => "}"

primitive TkLparen
  """
  The `(` symbol.
  """
  fun name(): String val => "TkLparen"
  fun text(): (String val | None) => "("

primitive TkRparen
  """
  The `)` symbol.
  """
  fun name(): String val => "TkRparen"
  fun text(): (String val | None) => ")"

primitive TkLsquare
  """
  The `[` symbol.
  """
  fun name(): String val => "TkLsquare"
  fun text(): (String val | None) => "["

primitive TkRsquare
  """
  The `]` symbol.
  """
  fun name(): String val => "TkRsquare"
  fun text(): (String val | None) => "]"

primitive TkComma
  """
  The `,` symbol.
  """
  fun name(): String val => "TkComma"
  fun text(): (String val | None) => ","

primitive TkDot
  """
  The `.` symbol.
  """
  fun name(): String val => "TkDot"
  fun text(): (String val | None) => "."

primitive TkTilde
  """
  The `~` symbol.
  """
  fun name(): String val => "TkTilde"
  fun text(): (String val | None) => "~"

primitive TkColon
  """
  The `:` symbol.
  """
  fun name(): String val => "TkColon"
  fun text(): (String val | None) => ":"

primitive TkSemi
  """
  The `;` symbol.
  """
  fun name(): String val => "TkSemi"
  fun text(): (String val | None) => ";"

primitive TkAssign
  """
  The `=` symbol.
  """
  fun name(): String val => "TkAssign"
  fun text(): (String val | None) => "="

primitive TkPlus
  """
  The `+` symbol.
  """
  fun name(): String val => "TkPlus"
  fun text(): (String val | None) => "+"

primitive TkMinus
  """
  The `-` symbol.
  """
  fun name(): String val => "TkMinus"
  fun text(): (String val | None) => "-"

primitive TkMultiply
  """
  The `*` symbol.
  """
  fun name(): String val => "TkMultiply"
  fun text(): (String val | None) => "*"

primitive TkDivide
  """
  The `/` symbol.
  """
  fun name(): String val => "TkDivide"
  fun text(): (String val | None) => "/"

primitive TkMod
  """
  The `%%` symbol.
  """
  fun name(): String val => "TkMod"
  fun text(): (String val | None) => "%%"

primitive TkRem
  """
  The `%` symbol.
  """
  fun name(): String val => "TkRem"
  fun text(): (String val | None) => "%"

primitive TkAt
  """
  The `@` symbol.
  """
  fun name(): String val => "TkAt"
  fun text(): (String val | None) => "@"

primitive TkLt
  """
  The `<` symbol.
  """
  fun name(): String val => "TkLt"
  fun text(): (String val | None) => "<"

primitive TkGt
  """
  The `>` symbol.
  """
  fun name(): String val => "TkGt"
  fun text(): (String val | None) => ">"

primitive TkPipe
  """
  The `|` symbol.
  """
  fun name(): String val => "TkPipe"
  fun text(): (String val | None) => "|"

primitive TkIsecttype
  """
  The `&` symbol.
  """
  fun name(): String val => "TkIsecttype"
  fun text(): (String val | None) => "&"

primitive TkEphemeral
  """
  The `^` symbol.
  """
  fun name(): String val => "TkEphemeral"
  fun text(): (String val | None) => "^"

primitive TkAliased
  """
  The `!` symbol.
  """
  fun name(): String val => "TkAliased"
  fun text(): (String val | None) => "!"

primitive TkQuestion
  """
  The `?` symbol.
  """
  fun name(): String val => "TkQuestion"
  fun text(): (String val | None) => "?"

primitive TkUnaryMinus
  """
  The `-` symbol.
  """
  fun name(): String val => "TkUnaryMinus"
  fun text(): (String val | None) => "-"

primitive TkConstant
  """
  The `#` symbol.
  """
  fun name(): String val => "TkConstant"
  fun text(): (String val | None) => "#"

primitive TkLparenNew
  """
  The `(` symbol.
  """
  fun name(): String val => "TkLparenNew"
  fun text(): (String val | None) => "("

primitive TkLsquareNew
  """
  The `[` symbol.
  """
  fun name(): String val => "TkLsquareNew"
  fun text(): (String val | None) => "["

primitive TkMinusTildeNew
  """
  The `-~` symbol.
  """
  fun name(): String val => "TkMinusTildeNew"
  fun text(): (String val | None) => "-~"

primitive TkMinusNew
  """
  The `-` symbol.
  """
  fun name(): String val => "TkMinusNew"
  fun text(): (String val | None) => "-"

primitive TkCompileIntrinsic
  """
  The `compile_intrinsic` keyword.
  """
  fun name(): String val => "TkCompileIntrinsic"
  fun text(): (String val | None) => "compile_intrinsic"

primitive TkUse
  """
  The `use` keyword.
  """
  fun name(): String val => "TkUse"
  fun text(): (String val | None) => "use"

primitive TkType
  """
  The `type` keyword.
  """
  fun name(): String val => "TkType"
  fun text(): (String val | None) => "type"

primitive TkInterface
  """
  The `interface` keyword.
  """
  fun name(): String val => "TkInterface"
  fun text(): (String val | None) => "interface"

primitive TkTrait
  """
  The `trait` keyword.
  """
  fun name(): String val => "TkTrait"
  fun text(): (String val | None) => "trait"

primitive TkPrimitive
  """
  The `primitive` keyword.
  """
  fun name(): String val => "TkPrimitive"
  fun text(): (String val | None) => "primitive"

primitive TkStruct
  """
  The `struct` keyword.
  """
  fun name(): String val => "TkStruct"
  fun text(): (String val | None) => "struct"

primitive TkClass
  """
  The `class` keyword.
  """
  fun name(): String val => "TkClass"
  fun text(): (String val | None) => "class"

primitive TkActor
  """
  The `actor` keyword.
  """
  fun name(): String val => "TkActor"
  fun text(): (String val | None) => "actor"

primitive TkObject
  """
  The `object` keyword.
  """
  fun name(): String val => "TkObject"
  fun text(): (String val | None) => "object"

primitive TkAs
  """
  The `as` keyword.
  """
  fun name(): String val => "TkAs"
  fun text(): (String val | None) => "as"

primitive TkIs
  """
  The `is` keyword.
  """
  fun name(): String val => "TkIs"
  fun text(): (String val | None) => "is"

primitive TkIsnt
  """
  The `isnt` keyword.
  """
  fun name(): String val => "TkIsnt"
  fun text(): (String val | None) => "isnt"

primitive TkVar
  """
  The `var` keyword.
  """
  fun name(): String val => "TkVar"
  fun text(): (String val | None) => "var"

primitive TkLet
  """
  The `let` keyword.
  """
  fun name(): String val => "TkLet"
  fun text(): (String val | None) => "let"

primitive TkEmbed
  """
  The `embed` keyword.
  """
  fun name(): String val => "TkEmbed"
  fun text(): (String val | None) => "embed"

primitive TkNew
  """
  The `new` keyword.
  """
  fun name(): String val => "TkNew"
  fun text(): (String val | None) => "new"

primitive TkFun
  """
  The `fun` keyword.
  """
  fun name(): String val => "TkFun"
  fun text(): (String val | None) => "fun"

primitive TkBe
  """
  The `be` keyword.
  """
  fun name(): String val => "TkBe"
  fun text(): (String val | None) => "be"

primitive TkIso
  """
  The `iso` keyword.
  """
  fun name(): String val => "TkIso"
  fun text(): (String val | None) => "iso"

primitive TkTrn
  """
  The `trn` keyword.
  """
  fun name(): String val => "TkTrn"
  fun text(): (String val | None) => "trn"

primitive TkRef
  """
  The `ref` keyword.
  """
  fun name(): String val => "TkRef"
  fun text(): (String val | None) => "ref"

primitive TkVal
  """
  The `val` keyword.
  """
  fun name(): String val => "TkVal"
  fun text(): (String val | None) => "val"

primitive TkBox
  """
  The `box` keyword.
  """
  fun name(): String val => "TkBox"
  fun text(): (String val | None) => "box"

primitive TkTag
  """
  The `tag` keyword.
  """
  fun name(): String val => "TkTag"
  fun text(): (String val | None) => "tag"

primitive TkThis
  """
  The `this` keyword.
  """
  fun name(): String val => "TkThis"
  fun text(): (String val | None) => "this"

primitive TkReturn
  """
  The `return` keyword.
  """
  fun name(): String val => "TkReturn"
  fun text(): (String val | None) => "return"

primitive TkBreak
  """
  The `break` keyword.
  """
  fun name(): String val => "TkBreak"
  fun text(): (String val | None) => "break"

primitive TkContinue
  """
  The `continue` keyword.
  """
  fun name(): String val => "TkContinue"
  fun text(): (String val | None) => "continue"

primitive TkConsume
  """
  The `consume` keyword.
  """
  fun name(): String val => "TkConsume"
  fun text(): (String val | None) => "consume"

primitive TkRecover
  """
  The `recover` keyword.
  """
  fun name(): String val => "TkRecover"
  fun text(): (String val | None) => "recover"

primitive TkIf
  """
  The `if` keyword.
  """
  fun name(): String val => "TkIf"
  fun text(): (String val | None) => "if"

primitive TkIfdef
  """
  The `ifdef` keyword.
  """
  fun name(): String val => "TkIfdef"
  fun text(): (String val | None) => "ifdef"

primitive TkIftypeSet
  """
  The `iftype` keyword.
  """
  fun name(): String val => "TkIftypeSet"
  fun text(): (String val | None) => "iftype"

primitive TkThen
  """
  The `then` keyword.
  """
  fun name(): String val => "TkThen"
  fun text(): (String val | None) => "then"

primitive TkElse
  """
  The `else` keyword.
  """
  fun name(): String val => "TkElse"
  fun text(): (String val | None) => "else"

primitive TkElseif
  """
  The `elseif` keyword.
  """
  fun name(): String val => "TkElseif"
  fun text(): (String val | None) => "elseif"

primitive TkEnd
  """
  The `end` keyword.
  """
  fun name(): String val => "TkEnd"
  fun text(): (String val | None) => "end"

primitive TkFor
  """
  The `for` keyword.
  """
  fun name(): String val => "TkFor"
  fun text(): (String val | None) => "for"

primitive TkIn
  """
  The `in` keyword.
  """
  fun name(): String val => "TkIn"
  fun text(): (String val | None) => "in"

primitive TkWhile
  """
  The `while` keyword.
  """
  fun name(): String val => "TkWhile"
  fun text(): (String val | None) => "while"

primitive TkDo
  """
  The `do` keyword.
  """
  fun name(): String val => "TkDo"
  fun text(): (String val | None) => "do"

primitive TkRepeat
  """
  The `repeat` keyword.
  """
  fun name(): String val => "TkRepeat"
  fun text(): (String val | None) => "repeat"

primitive TkUntil
  """
  The `until` keyword.
  """
  fun name(): String val => "TkUntil"
  fun text(): (String val | None) => "until"

primitive TkMatch
  """
  The `match` keyword.
  """
  fun name(): String val => "TkMatch"
  fun text(): (String val | None) => "match"

primitive TkWhere
  """
  The `where` keyword.
  """
  fun name(): String val => "TkWhere"
  fun text(): (String val | None) => "where"

primitive TkTry
  """
  The `try` keyword.
  """
  fun name(): String val => "TkTry"
  fun text(): (String val | None) => "try"

primitive TkWith
  """
  The `with` keyword.
  """
  fun name(): String val => "TkWith"
  fun text(): (String val | None) => "with"

primitive TkError
  """
  The `error` keyword.
  """
  fun name(): String val => "TkError"
  fun text(): (String val | None) => "error"

primitive TkCompileError
  """
  The `compile_error` keyword.
  """
  fun name(): String val => "TkCompileError"
  fun text(): (String val | None) => "compile_error"

primitive TkNot
  """
  The `not` keyword.
  """
  fun name(): String val => "TkNot"
  fun text(): (String val | None) => "not"

primitive TkAnd
  """
  The `and` keyword.
  """
  fun name(): String val => "TkAnd"
  fun text(): (String val | None) => "and"

primitive TkOr
  """
  The `or` keyword.
  """
  fun name(): String val => "TkOr"
  fun text(): (String val | None) => "or"

primitive TkXor
  """
  The `xor` keyword.
  """
  fun name(): String val => "TkXor"
  fun text(): (String val | None) => "xor"

primitive TkDigestof
  """
  The `digestof` keyword.
  """
  fun name(): String val => "TkDigestof"
  fun text(): (String val | None) => "digestof"

primitive TkAddress
  """
  The `addressof` keyword.
  """
  fun name(): String val => "TkAddress"
  fun text(): (String val | None) => "addressof"

primitive TkLocation
  """
  The `__loc` keyword.
  """
  fun name(): String val => "TkLocation"
  fun text(): (String val | None) => "__loc"

primitive TkTrue
  """
  The `true` keyword.
  """
  fun name(): String val => "TkTrue"
  fun text(): (String val | None) => "true"

primitive TkFalse
  """
  The `false` keyword.
  """
  fun name(): String val => "TkFalse"
  fun text(): (String val | None) => "false"

primitive TkCapRead
  """
  The `#read` keyword.
  """
  fun name(): String val => "TkCapRead"
  fun text(): (String val | None) => "#read"

primitive TkCapSend
  """
  The `#send` keyword.
  """
  fun name(): String val => "TkCapSend"
  fun text(): (String val | None) => "#send"

primitive TkCapShare
  """
  The `#share` keyword.
  """
  fun name(): String val => "TkCapShare"
  fun text(): (String val | None) => "#share"

primitive TkCapAlias
  """
  The `#alias` keyword.
  """
  fun name(): String val => "TkCapAlias"
  fun text(): (String val | None) => "#alias"

primitive TkCapAny
  """
  The `#any` keyword.
  """
  fun name(): String val => "TkCapAny"
  fun text(): (String val | None) => "#any"

primitive TkTestNoSeq
  """
  The `$noseq` keyword.
  """
  fun name(): String val => "TkTestNoSeq"
  fun text(): (String val | None) => "$noseq"

primitive TkTestSeqScope
  """
  The `$scope` keyword.
  """
  fun name(): String val => "TkTestSeqScope"
  fun text(): (String val | None) => "$scope"

primitive TkTestTryNoCheck
  """
  The `$try_no_check` keyword.
  """
  fun name(): String val => "TkTestTryNoCheck"
  fun text(): (String val | None) => "$try_no_check"

primitive TkTestAliased
  """
  The `$aliased` keyword.
  """
  fun name(): String val => "TkTestAliased"
  fun text(): (String val | None) => "$aliased"

primitive TkTestUpdatearg
  """
  The `$updatearg` keyword.
  """
  fun name(): String val => "TkTestUpdatearg"
  fun text(): (String val | None) => "$updatearg"

primitive TkTestExtra
  """
  The `$extra` keyword.
  """
  fun name(): String val => "TkTestExtra"
  fun text(): (String val | None) => "$extra"

primitive TkIfdefand
  """
  The `$ifdefand` keyword.
  """
  fun name(): String val => "TkIfdefand"
  fun text(): (String val | None) => "$ifdefand"

primitive TkIfdefor
  """
  The `$ifdefor` keyword.
  """
  fun name(): String val => "TkIfdefor"
  fun text(): (String val | None) => "$ifdefor"

primitive TkIfdefnot
  """
  The `$ifdefnot` keyword.
  """
  fun name(): String val => "TkIfdefnot"
  fun text(): (String val | None) => "$ifdefnot"

primitive TkIfdefflag
  """
  The `$flag` keyword.
  """
  fun name(): String val => "TkIfdefflag"
  fun text(): (String val | None) => "$flag"

primitive TkMatchCapture
  """
  The `$let` keyword.
  """
  fun name(): String val => "TkMatchCapture"
  fun text(): (String val | None) => "$let"

primitive TkMatchDontcare
  """
  The `$dontcare` keyword.
  """
  fun name(): String val => "TkMatchDontcare"
  fun text(): (String val | None) => "$dontcare"

primitive TkIftype
  """
  The `$iftype` keyword.
  """
  fun name(): String val => "TkIftype"
  fun text(): (String val | None) => "$iftype"

primitive TkId
  """
  An identifier.
  """
  fun name(): String val => "TkId"
  fun text(): (String val | None) => None

primitive TkString
  """
  A string literal.
  """
  fun name(): String val => "TkString"
  fun text(): (String val | None) => None

primitive TkInt
  """
  An integer literal.
  """
  fun name(): String val => "TkInt"
  fun text(): (String val | None) => None

primitive TkFloat
  """
  A float literal.
  """
  fun name(): String val => "TkFloat"
  fun text(): (String val | None) => None

primitive TkWhitespace
  """
  A run of spaces, tabs or newlines.
  """
  fun name(): String val => "TkWhitespace"
  fun text(): (String val | None) => None

primitive TkLineComment
  """
  A `//` comment, up to but not including the newline.
  """
  fun name(): String val => "TkLineComment"
  fun text(): (String val | None) => None

primitive TkNestedComment
  """
  A `/* */` comment, which may nest.
  """
  fun name(): String val => "TkNestedComment"
  fun text(): (String val | None) => None

primitive TkEof
  """
  The end of the source.
  """
  fun name(): String val => "TkEof"
  fun text(): (String val | None) => None

primitive TkLexError
  """
  Bytes the lexer could not interpret.
  """
  fun name(): String val => "TkLexError"
  fun text(): (String val | None) => None

type TokenKind is
  ( TkEllipsis
  | TkArrow
  | TkDblarrow
  | TkLshiftTilde
  | TkRshiftTilde
  | TkEqTilde
  | TkNeTilde
  | TkLeTilde
  | TkGeTilde
  | TkLtTilde
  | TkGtTilde
  | TkPlusTilde
  | TkMinusTilde
  | TkMultiplyTilde
  | TkDivideTilde
  | TkModTilde
  | TkRemTilde
  | TkLshift
  | TkRshift
  | TkEq
  | TkNe
  | TkLe
  | TkGe
  | TkChain
  | TkSubtype
  | TkBackslash
  | TkAtLbrace
  | TkLbrace
  | TkRbrace
  | TkLparen
  | TkRparen
  | TkLsquare
  | TkRsquare
  | TkComma
  | TkDot
  | TkTilde
  | TkColon
  | TkSemi
  | TkAssign
  | TkPlus
  | TkMinus
  | TkMultiply
  | TkDivide
  | TkMod
  | TkRem
  | TkAt
  | TkLt
  | TkGt
  | TkPipe
  | TkIsecttype
  | TkEphemeral
  | TkAliased
  | TkQuestion
  | TkUnaryMinus
  | TkConstant
  | TkLparenNew
  | TkLsquareNew
  | TkMinusTildeNew
  | TkMinusNew
  | TkCompileIntrinsic
  | TkUse
  | TkType
  | TkInterface
  | TkTrait
  | TkPrimitive
  | TkStruct
  | TkClass
  | TkActor
  | TkObject
  | TkAs
  | TkIs
  | TkIsnt
  | TkVar
  | TkLet
  | TkEmbed
  | TkNew
  | TkFun
  | TkBe
  | TkIso
  | TkTrn
  | TkRef
  | TkVal
  | TkBox
  | TkTag
  | TkThis
  | TkReturn
  | TkBreak
  | TkContinue
  | TkConsume
  | TkRecover
  | TkIf
  | TkIfdef
  | TkIftypeSet
  | TkThen
  | TkElse
  | TkElseif
  | TkEnd
  | TkFor
  | TkIn
  | TkWhile
  | TkDo
  | TkRepeat
  | TkUntil
  | TkMatch
  | TkWhere
  | TkTry
  | TkWith
  | TkError
  | TkCompileError
  | TkNot
  | TkAnd
  | TkOr
  | TkXor
  | TkDigestof
  | TkAddress
  | TkLocation
  | TkTrue
  | TkFalse
  | TkCapRead
  | TkCapSend
  | TkCapShare
  | TkCapAlias
  | TkCapAny
  | TkTestNoSeq
  | TkTestSeqScope
  | TkTestTryNoCheck
  | TkTestAliased
  | TkTestUpdatearg
  | TkTestExtra
  | TkIfdefand
  | TkIfdefor
  | TkIfdefnot
  | TkIfdefflag
  | TkMatchCapture
  | TkMatchDontcare
  | TkIftype
  | TkId
  | TkString
  | TkInt
  | TkFloat
  | TkWhitespace
  | TkLineComment
  | TkNestedComment
  | TkEof
  | TkLexError
  )
  """
  Every kind of token the lexer can produce.

  `text()` is the token's exact source text where the kind fixes it,
  and `None` where it does not -- an identifier, a literal, a comment,
  a run of whitespace. Only the latter need their text stored.
  """

primitive Keywords
  """
  Recognises the keywords, for a lexer that has just scanned something
  shaped like an identifier.
  """
  fun apply(s: String box): (TokenKind | None) =>
    match s
    | "compile_intrinsic" => TkCompileIntrinsic
    | "use" => TkUse
    | "type" => TkType
    | "interface" => TkInterface
    | "trait" => TkTrait
    | "primitive" => TkPrimitive
    | "struct" => TkStruct
    | "class" => TkClass
    | "actor" => TkActor
    | "object" => TkObject
    | "as" => TkAs
    | "is" => TkIs
    | "isnt" => TkIsnt
    | "var" => TkVar
    | "let" => TkLet
    | "embed" => TkEmbed
    | "new" => TkNew
    | "fun" => TkFun
    | "be" => TkBe
    | "iso" => TkIso
    | "trn" => TkTrn
    | "ref" => TkRef
    | "val" => TkVal
    | "box" => TkBox
    | "tag" => TkTag
    | "this" => TkThis
    | "return" => TkReturn
    | "break" => TkBreak
    | "continue" => TkContinue
    | "consume" => TkConsume
    | "recover" => TkRecover
    | "if" => TkIf
    | "ifdef" => TkIfdef
    | "iftype" => TkIftypeSet
    | "then" => TkThen
    | "else" => TkElse
    | "elseif" => TkElseif
    | "end" => TkEnd
    | "for" => TkFor
    | "in" => TkIn
    | "while" => TkWhile
    | "do" => TkDo
    | "repeat" => TkRepeat
    | "until" => TkUntil
    | "match" => TkMatch
    | "where" => TkWhere
    | "try" => TkTry
    | "with" => TkWith
    | "error" => TkError
    | "compile_error" => TkCompileError
    | "not" => TkNot
    | "and" => TkAnd
    | "or" => TkOr
    | "xor" => TkXor
    | "digestof" => TkDigestof
    | "addressof" => TkAddress
    | "__loc" => TkLocation
    | "true" => TkTrue
    | "false" => TkFalse
    | "#read" => TkCapRead
    | "#send" => TkCapSend
    | "#share" => TkCapShare
    | "#alias" => TkCapAlias
    | "#any" => TkCapAny
    | "$noseq" => TkTestNoSeq
    | "$scope" => TkTestSeqScope
    | "$try_no_check" => TkTestTryNoCheck
    | "$aliased" => TkTestAliased
    | "$updatearg" => TkTestUpdatearg
    | "$extra" => TkTestExtra
    | "$ifdefand" => TkIfdefand
    | "$ifdefor" => TkIfdefor
    | "$ifdefnot" => TkIfdefnot
    | "$flag" => TkIfdefflag
    | "$let" => TkMatchCapture
    | "$dontcare" => TkMatchDontcare
    | "$iftype" => TkIftype
    else
      None
    end

primitive Symbols
  """
  The symbols a scanner can reach, longest first so that taking the
  first match takes the longest -- `<<~` before `<<` before `<`.

  ponyc's table lists some texts twice and its scan takes the first,
  so these are the reachable entries only. Absent, and reachable by
  other means:
  `-` as TkUnaryMinus.
  `(` as TkLparenNew.
  `[` as TkLsquareNew.
  `-~` as TkMinusTildeNew.
  `-` as TkMinusNew.
  """
  fun apply(): Array[(String val, TokenKind)] val =>
    [
      ("...", TkEllipsis)
      ("<<~", TkLshiftTilde)
      (">>~", TkRshiftTilde)
      ("==~", TkEqTilde)
      ("!=~", TkNeTilde)
      ("<=~", TkLeTilde)
      (">=~", TkGeTilde)
      ("%%~", TkModTilde)
      ("->", TkArrow)
      ("=>", TkDblarrow)
      ("<~", TkLtTilde)
      (">~", TkGtTilde)
      ("+~", TkPlusTilde)
      ("-~", TkMinusTilde)
      ("*~", TkMultiplyTilde)
      ("/~", TkDivideTilde)
      ("%~", TkRemTilde)
      ("<<", TkLshift)
      (">>", TkRshift)
      ("==", TkEq)
      ("!=", TkNe)
      ("<=", TkLe)
      (">=", TkGe)
      (".>", TkChain)
      ("<:", TkSubtype)
      ("@{", TkAtLbrace)
      ("%%", TkMod)
      ("\\", TkBackslash)
      ("{", TkLbrace)
      ("}", TkRbrace)
      ("(", TkLparen)
      (")", TkRparen)
      ("[", TkLsquare)
      ("]", TkRsquare)
      (",", TkComma)
      (".", TkDot)
      ("~", TkTilde)
      (":", TkColon)
      (";", TkSemi)
      ("=", TkAssign)
      ("+", TkPlus)
      ("-", TkMinus)
      ("*", TkMultiply)
      ("/", TkDivide)
      ("%", TkRem)
      ("@", TkAt)
      ("<", TkLt)
      (">", TkGt)
      ("|", TkPipe)
      ("&", TkIsecttype)
      ("^", TkEphemeral)
      ("!", TkAliased)
      ("?", TkQuestion)
      ("#", TkConstant)
    ]

primitive AllTokenKinds
  """
  Every token kind, for tests and for anything that must be shown to
  handle all of them.
  """
  fun apply(): Array[TokenKind] val =>
    [
      TkEllipsis
      TkArrow
      TkDblarrow
      TkLshiftTilde
      TkRshiftTilde
      TkEqTilde
      TkNeTilde
      TkLeTilde
      TkGeTilde
      TkLtTilde
      TkGtTilde
      TkPlusTilde
      TkMinusTilde
      TkMultiplyTilde
      TkDivideTilde
      TkModTilde
      TkRemTilde
      TkLshift
      TkRshift
      TkEq
      TkNe
      TkLe
      TkGe
      TkChain
      TkSubtype
      TkBackslash
      TkAtLbrace
      TkLbrace
      TkRbrace
      TkLparen
      TkRparen
      TkLsquare
      TkRsquare
      TkComma
      TkDot
      TkTilde
      TkColon
      TkSemi
      TkAssign
      TkPlus
      TkMinus
      TkMultiply
      TkDivide
      TkMod
      TkRem
      TkAt
      TkLt
      TkGt
      TkPipe
      TkIsecttype
      TkEphemeral
      TkAliased
      TkQuestion
      TkUnaryMinus
      TkConstant
      TkLparenNew
      TkLsquareNew
      TkMinusTildeNew
      TkMinusNew
      TkCompileIntrinsic
      TkUse
      TkType
      TkInterface
      TkTrait
      TkPrimitive
      TkStruct
      TkClass
      TkActor
      TkObject
      TkAs
      TkIs
      TkIsnt
      TkVar
      TkLet
      TkEmbed
      TkNew
      TkFun
      TkBe
      TkIso
      TkTrn
      TkRef
      TkVal
      TkBox
      TkTag
      TkThis
      TkReturn
      TkBreak
      TkContinue
      TkConsume
      TkRecover
      TkIf
      TkIfdef
      TkIftypeSet
      TkThen
      TkElse
      TkElseif
      TkEnd
      TkFor
      TkIn
      TkWhile
      TkDo
      TkRepeat
      TkUntil
      TkMatch
      TkWhere
      TkTry
      TkWith
      TkError
      TkCompileError
      TkNot
      TkAnd
      TkOr
      TkXor
      TkDigestof
      TkAddress
      TkLocation
      TkTrue
      TkFalse
      TkCapRead
      TkCapSend
      TkCapShare
      TkCapAlias
      TkCapAny
      TkTestNoSeq
      TkTestSeqScope
      TkTestTryNoCheck
      TkTestAliased
      TkTestUpdatearg
      TkTestExtra
      TkIfdefand
      TkIfdefor
      TkIfdefnot
      TkIfdefflag
      TkMatchCapture
      TkMatchDontcare
      TkIftype
      TkId
      TkString
      TkInt
      TkFloat
      TkWhitespace
      TkLineComment
      TkNestedComment
      TkEof
      TkLexError
    ]

primitive NewlineForm
  """
  Maps a symbol to its newline form. Pony distinguishes a `(` that
  opens a call from one that opens a grouped expression by whether a
  newline precedes it, and likewise for `[` and `-`. ponyc does this
  in `newline_symbols`; this is that function.
  """
  fun apply(k: TokenKind, after_newline: Bool): TokenKind =>
    if not after_newline then
      k
    else
      match k
      | TkLparen => TkLparenNew
      | TkLsquare => TkLsquareNew
      | TkMinus => TkMinusNew
      | TkMinusTilde => TkMinusTildeNew
      else
        k
      end
    end
