#!/usr/bin/env python3
"""Generate pony_syntax/token_kind.pony from ponyc's lexer tables.

The token kinds a Pony lexer can produce are exactly ponyc's `symbols` and
`keywords` tables, plus the variable-text tokens the lexer builds directly,
plus the trivia kinds ponyc has no use for and a lossless tree does.

Re-run this when ponyc's tables change:

    tools/gen_token_kinds.py <path-to-ponyc>/src/libponyc/ast/lexer.c
"""
import re
import sys

# Tokens the lexer produces whose text is not fixed by their kind, and so is
# not in any of ponyc's tables.
VARIABLE = [
    ("TK_ID", "an identifier"),
    ("TK_STRING", "a string literal"),
    ("TK_INT", "an integer literal"),
    ("TK_FLOAT", "a float literal"),
]

# Kinds ponyc does not need. A batch compiler discards trivia and stops at the
# first error; a language server keeps both.
EXTRA = [
    ("TK_WHITESPACE", "a run of spaces, tabs or newlines"),
    ("TK_LINE_COMMENT", "a `//` comment, up to but not including the newline"),
    ("TK_NESTED_COMMENT", "a `/* */` comment, which may nest"),
    ("TK_EOF", "the end of the source"),
    ("TK_LEX_ERROR", "bytes the lexer could not interpret"),
]


def camel(tk):
    """TK_LSHIFT_TILDE -> TkLshiftTilde"""
    return "Tk" + "".join(p.capitalize() for p in tk[3:].split("_"))


def c_unescape(s):
    return s.replace("\\\\", "\\").replace('\\"', '"')


def pony_escape(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def table(src, name):
    m = re.search(
        r"static const lextoken_t %s\[\] =\s*\{(.*?)\n\};" % name, src, re.S)
    if m is None:
        raise SystemExit("could not find table: " + name)
    return [(c_unescape(t), i) for t, i in
            re.findall(r'\{\s*"((?:[^"\\]|\\.)*)"\s*,\s*(TK_[A-Z0-9_]+)\s*\}',
                       m.group(1))]


def main(lexer_c):
    src = open(lexer_c).read()
    symbols = table(src, "symbols")
    keywords = table(src, "keywords")

    out = []
    w = out.append
    w("// Token kinds, and the fixed text of those that have any.")
    w("//")
    w("// Generated by `tools/gen_token_kinds.py` from ponyc's `lexer.c`. The")
    w("// kinds are ponyc's `symbols` and `keywords` tables verbatim, plus the")
    w("// tokens whose text varies, plus the trivia and error kinds a lossless")
    w("// tree needs and a batch compiler does not. Do not edit by hand.")
    w("")

    entries = []  # (pony name, fixed text or None, docstring)
    for text, tk in symbols:
        entries.append((camel(tk), text, "The `%s` symbol." % text))
    for text, tk in keywords:
        entries.append((camel(tk), text, "The `%s` keyword." % text))
    for tk, desc in VARIABLE + EXTRA:
        entries.append((camel(tk), None, "%s." % desc.capitalize()))

    seen = {}
    for name, text, doc in entries:
        if name in seen:
            raise SystemExit("duplicate kind: " + name)
        seen[name] = True
        w("primitive %s" % name)
        w('  """')
        w("  %s" % doc)
        w('  """')
        w('  fun name(): String val => "%s"' % name)
        if text is None:
            w("  fun text(): (String val | None) => None")
        else:
            w('  fun text(): (String val | None) => "%s"' % pony_escape(text))
        w("")

    names = [n for n, _, _ in entries]
    w("type TokenKind is")
    for i, n in enumerate(names):
        lead = "  ( " if i == 0 else "  | "
        w(lead + n)
    w("  )")
    w('  """')
    w("  Every kind of token the lexer can produce.")
    w("")
    w("  `text()` is the token's exact source text where the kind fixes it,")
    w("  and `None` where it does not -- an identifier, a literal, a comment,")
    w("  a run of whitespace. Only the latter need their text stored.")
    w('  """')
    w("")

    # Keyword lookup: the lexer scans an identifier, then asks whether it is
    # one of these.
    w("primitive Keywords")
    w('  """')
    w("  Recognises the keywords, for a lexer that has just scanned something")
    w("  shaped like an identifier.")
    w('  """')
    w("  fun apply(s: String box): (TokenKind | None) =>")
    w("    match s")
    for text, tk in keywords:
        w('    | "%s" => %s' % (pony_escape(text), camel(tk)))
    w("    else")
    w("      None")
    w("    end")
    w("")

    # Symbols the scanner can actually reach. ponyc's table lists some texts
    # more than once -- "(" as both TK_LPAREN and TK_LPAREN_NEW -- and its
    # scan takes the first, so the later entries are unreachable. They are
    # real kinds, produced by `NewlineForm` and by the parser, but a scan
    # table containing them would never match them and would invite the
    # reader to think otherwise.
    scan, dropped = [], []
    seen_text = set()
    for text, tk in symbols:
        if text in seen_text:
            dropped.append((text, tk))
        else:
            seen_text.add(text)
            scan.append((text, tk))

    w("primitive Symbols")
    w('  """')
    w("  The symbols a scanner can reach, longest first so that taking the")
    w("  first match takes the longest -- `<<~` before `<<` before `<`.")
    w("")
    w("  ponyc's table lists some texts twice and its scan takes the first,")
    w("  so these are the reachable entries only. Absent, and reachable by")
    w("  other means:")
    for text, tk in dropped:
        w("  `%s` as %s." % (text, camel(tk)))
    w('  """')
    w("  fun apply(): Array[(String val, TokenKind)] val =>")
    w("    [")
    for text, tk in sorted(scan, key=lambda e: -len(e[0])):
        w('      ("%s", %s)' % (pony_escape(text), camel(tk)))
    w("    ]")
    w("")

    w("primitive AllTokenKinds")
    w('  """')
    w("  Every token kind, for tests and for anything that must be shown to")
    w("  handle all of them.")
    w('  """')
    w("  fun apply(): Array[TokenKind] val =>")
    w("    [")
    for n in names:
        w("      " + n)
    w("    ]")
    w("")

    w("primitive NewlineForm")
    w('  """')
    w("  Maps a symbol to its newline form. Pony distinguishes a `(` that")
    w("  opens a call from one that opens a grouped expression by whether a")
    w("  newline precedes it, and likewise for `[` and `-`. ponyc does this")
    w("  in `newline_symbols`; this is that function.")
    w('  """')
    w("  fun apply(k: TokenKind, after_newline: Bool): TokenKind =>")
    w("    if not after_newline then")
    w("      k")
    w("    else")
    w("      match k")
    w("      | TkLparen => TkLparenNew")
    w("      | TkLsquare => TkLsquareNew")
    w("      | TkMinus => TkMinusNew")
    w("      | TkMinusTilde => TkMinusTildeNew")
    w("      else")
    w("        k")
    w("      end")
    w("    end")

    return "\n".join(out) + "\n"


if __name__ == "__main__":
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    sys.stdout.write(main(sys.argv[1]))
